package demo.entities;
// Generated Oct 18, 2016 7:35:42 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "demohibernate")
public class Account implements java.io.Serializable {

	private String username;
	private String password;
	private String fullName;
	private Date birthday;
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Account() {
	}

	public Account(String username, String password, String fullName, Date birthday) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.birthday = birthday;
	}

	public Account(String username, String password, String fullName, Date birthday, Set<Role> roles,
			Set<Orders> orderses) {
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.birthday = birthday;
		this.roles = roles;
		this.orderses = orderses;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fullName", nullable = false, length = 250)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", nullable = false, length = 0)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "permission", catalog = "demohibernate", joinColumns = {
			@JoinColumn(name = "username", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "roleId", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
