package demo.entities;
// Generated Dec 10, 2017 12:25:33 PM by Hibernate Tools 5.2.0.Beta1

import demo.entities.*;
import java.util.*;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name = "answer", catalog = "onlinequiz")
public class Answer implements java.io.Serializable {

	private Integer id;
	private Question question;
	private String content;
	private boolean istrue;
	private boolean isStudent;
	private List<Result> results = new ArrayList<Result>(0);
	private String prefix;

	public Answer() {
	}

	public Answer(Question question, String content, boolean istrue) {
		this.question = question;
		this.content = content;
		this.istrue = istrue;
	}

	public Answer(Question question, String content, boolean istrue, List<Result> results) {
		this.question = question;
		this.content = content;
		this.istrue = istrue;
		this.results = results;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "questionid", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name="prefix", nullable = false, length = 1)
	public String getPrefix() {
        return prefix;
    }

    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    @Column(name = "content", nullable = false, length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "isStudent", nullable = false)
	public boolean isIsStudent() {
        return isStudent;
    }

    public void setIsStudent(boolean isStudent) {
        this.isStudent = isStudent;
    }

    @Column(name = "istrue", nullable = false)
	public boolean isIstrue() {
		return this.istrue;
	}

	public void setIstrue(boolean istrue) {
		this.istrue = istrue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "answer")
	public List<Result> getResults() {
		return this.results;
	}

	public void setResults(List<Result> results) {
		this.results = results;
	}

}
