package demo.entities;
// Generated Oct 18, 2016 7:35:42 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderdetailId generated by hbm2java
 */
@Embeddable
public class OrderdetailId implements java.io.Serializable {

	private int orderId;
	private int productId;

	public OrderdetailId() {
	}

	public OrderdetailId(int orderId, int productId) {
		this.orderId = orderId;
		this.productId = productId;
	}

	@Column(name = "orderId", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "productId", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderdetailId))
			return false;
		OrderdetailId castOther = (OrderdetailId) other;

		return (this.getOrderId() == castOther.getOrderId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
