package demo.entities;
// Generated Nov 29, 2017 7:25:01 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import demo.entities.*;
/**
 * Questiontype generated by hbm2java
 */
@Entity
@Table(name = "questiontype", catalog = "onlinequiz")
public class Questiontype implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Question> questions = new HashSet<Question>(0);

	public Questiontype() {
	}

	public Questiontype(String name) {
		this.name = name;
	}

	public Questiontype(String name, Set<Question> questions) {
		this.name = name;
		this.questions = questions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questiontype")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
