package demo.entities;
// Generated Dec 10, 2017 12:25:33 PM by Hibernate Tools 5.2.0.Beta1

import demo.entities.*;
import java.util.*;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "onlinequiz")
public class Role implements java.io.Serializable {

	private Integer id;
	private String name;
	private List<AccountRole> accountRoles = new ArrayList<AccountRole>();
	
	public Role() {
        super();
        // TODO Auto-generated constructor stub
    }

    public Role(Integer id, String name, List<AccountRole> accountRoles) {
        super();
        this.id = id;
        this.name = name;
        this.accountRoles = accountRoles;
    }

    @Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(mappedBy ="primaryKey.role", cascade = CascadeType.ALL )
    public List<AccountRole> getAccountRoles() {
        return accountRoles;
    }

    public void setAccountRoles(List<AccountRole> accountRoles) {
        this.accountRoles = accountRoles;
    }
    public void addAccountRole(AccountRole accountRole) {
        this.accountRoles.add(accountRole);
    }
    

	

}
